/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

public class App {

    public static void main(String[] args) {
        Menu menu = new Menu();
        menu.afegir_plat("Kebab", 5.99);
        String llista = menu.llistar_menu();
        System.out.println(llista);
    }
}


/*
Gestió del Menú:
    · afegir_plat(nom, preu): Afegeix un nou plat al menú amb el seu preu.
    · eliminar_plat(nom): Elimina un plat del menú.
    · llistar_menu(): Mostra tots els plats disponibles al menú.
Gestió de Comandes:
    · crear_comanda(): Crea una nova comanda.
    · afegir_plat_comanda(id_comanda, nom_plat): Afegeix un plat a la comanda basant-se en el nom.
    · calcular_total_comanda(id_comanda): Calcula el total de la comanda.
    · mostrar_comanda(id_comanda): Mostra tots els plats de la comanda.
*/