/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
    public class GestorLibroClubTest {
    
        @Test
        void registrarUsuarioTest() {
            GestorLibroClub gestor = new GestorLibroClub();s
            gestor.registrarUsuario("nombre-Usuario", "correo-usuario@test.es");
            assertEquals("correo-usuario@test.es", gestor.usuarios.get(0)[1]);
        }
    
        @Test
        void eliminarUsuarioTest() { 
            GestorLibroClub gestor = new GestorLibroClub();
            gestor.eliminarUsuario("nombre-Usuario");
            assertEquals(0, gestor.usuarios.size());
        }
    
        @Test
        void anadirLibroTest() {
            GestorLibroClub gestor = new GestorLibroClub();
            gestor.anadirLibro("titulo-Libro", "nombre-Autor");
            assertTrue(gestor.libros.contains("titulo-Libro por nombre-Autor"));
        }
    
        @Test
        void eliminarLibroTest() {
            GestorLibroClub gestor = new GestorLibroClub();
            gestor.eliminarLibro("titulo-Libro");
            assertFalse(gestor.libros.contains("titulo-Libro por nombre-Autor"));
            assertFalse(gestor.lecturas.stream().anyMatch(lecturasUsuario -> lecturasUsuario.contains("titulo-Libro")));
        }

    }
}